name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # TODO: Setup cache
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.4

      - run: bun install --frozen-lockfile
      - run: bun run lint

  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ignore-platform-reqs"
      - run: ./vendor/bin/pint -v --test
